import type { Metadata } from 'next';

import SelectLoanTypeForm from './_components/select-loan-type';

export const metadata: Metadata = {
  title: 'انتخاب نوع تسهیلات',
  description: 'Generated by create next app'
};

const Page = () => {
  return <SelectLoanTypeForm />;
};

export default Page;
