import type { Metadata } from 'next';

import { BankInfoForm } from 'components';

export const metadata: Metadata = {
  title: 'اطلاعات حساب بانکی',
  description: 'Generated by create next app'
};

const Page = () => {
  return <BankInfoForm />;
};

export default Page;
