import './globals.css';
import type { Metadata } from 'next';

import IranSans from '../../public/fonts/fonts';
import { Layout } from 'components';
import { ReduxProvider } from 'libs/redux';

export const metadata: Metadata = {
  title: 'لیست تسهیلات',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className={`${IranSans.variable}`}>
      <body>
        <ReduxProvider>
          <Layout>{children}</Layout>
        </ReduxProvider>
      </body>
    </html>
  );
}
