import type { Metadata } from 'next';

import SubmitLoanForm from './_components/submit-loan-form';

export const metadata: Metadata = {
  title: 'ثبت درخواست',
  description: 'Generated by create next app'
};

const Page = () => {
  return <SubmitLoanForm />;
};

export default Page;
